# Generated by Django 2.2.4 on 2019-08-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(default='', max_length=100)),
                ('nome_usuario', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=255)),
                ('celular', models.CharField(default='', max_length=14)),
                ('senha', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
